/**
 * generated by Xtext 2.14.0.RC1
 */
package org.example.domainmodel.ide;

import org.example.domainmodel.ide.AbstractDomainmodelIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DomainmodelIdeModule extends AbstractDomainmodelIdeModule {
}
