/*
 * generated by Xtext 2.14.0.RC1
 */
package org.example.domainmodel.ide


/**
 * Use this class to register ide components.
 */
class DomainmodelIdeModule extends AbstractDomainmodelIdeModule {
}
