/**
 * generated by Xtext 2.14.0
 */
package org.example.domainmodel.domainmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.domainmodel.domainmodel.Type#getSd <em>Sd</em>}</li>
 * </ul>
 *
 * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
  /**
   * Returns the value of the '<em><b>Sd</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sd</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sd</em>' containment reference.
   * @see #setSd(DataType)
   * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getType_Sd()
   * @model containment="true"
   * @generated
   */
  DataType getSd();

  /**
   * Sets the value of the '{@link org.example.domainmodel.domainmodel.Type#getSd <em>Sd</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sd</em>' containment reference.
   * @see #getSd()
   * @generated
   */
  void setSd(DataType value);

} // Type
