/*
 * generated by Xtext 2.14.0
 */
package org.example.domainmodel.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.example.domainmodel.domainmodel.Domainmodel
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(DomainmodelInjectorProvider)
class DomainmodelParsingTest {
	@Inject
	ParseHelper<Domainmodel> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			DATABASE name bancoNew
			
			entity Blog {
			    title: VARCHAR(500)
			    many Post: INT
			} 
			entity HasAuthor {
			    author: VARCHAR(1000)
			} 
			entity Post extends HasAuthor {
			    title: VARCHAR(1000)
			    content: VARCHAR(1000)
			    many Comment: INT
			} 
			entity Comment extends HasAuthor {
			    content: VARCHAR(1000)
			}
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
	@Test
	def void loadModel2() {
		val result = parseHelper.parse('''
			DATABASE name MarketDB
					
					entity Market {
					    title: VARCHAR(100)
					    many Products: INT
					}
					 
					entity HasEmployee {
					    name: VARCHAR(100)
					    salary: NUMBER
					}
					entity Products {
					    name: VARCHAR(1000)
					    description: VARCHAR(1000)
					    price: NUMBER
					}
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}

	@Test
	def void loadModel3() {
		val result = parseHelper.parse('''
			DATABASE name varchar
					
					entity LibraryDB{
					    title: VARCHAR(100)
					}
					 
					entity Author{
						name: VARCHAR(100)
						age: INT
					}
					entity Book extends Author{
					    name: VARCHAR(100)
					    description: TEXT(150)
					    company: VARCHAR(100)
					    id_author: INT	
					}
			''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}

	@Test
	def void loadModel4() {
		val result = parseHelper.parse('''
			DATABASE name SchoolDB
					
					entity Discipline {
					    title VARCHAR(100)
					    many students INT
					}
					 
					entity Teacher extends Discipline{
						name VARCHAR(100)
						age INT
						specialty VARCHAR(50)
					}
					entity Student extends Discipline{
						id: INT
						name: VARCHAR(100)
					}
					entity Note extends Student{
						value: NUMBER
						
					}
			''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}

}
