/*
 * generated by Xtext 2.14.0.RC1
 */
package org.example.domainmodel.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class DomainmodelUiModule extends AbstractDomainmodelUiModule {
}
