/**
 * generated by Xtext 2.14.0
 */
package org.example.domainmodel.tests;

import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.example.domainmodel.domainmodel.Domainmodel;
import org.example.domainmodel.tests.DomainmodelInjectorProvider;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(DomainmodelInjectorProvider.class)
@SuppressWarnings("all")
public class DomainmodelParsingTest {
  @Inject
  private ParseHelper<Domainmodel> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("DATABASE name bancoNew");
      _builder.newLine();
      _builder.newLine();
      _builder.append("entity Blog {");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("title: VARCHAR(500)");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("many Post: INT");
      _builder.newLine();
      _builder.append("} ");
      _builder.newLine();
      _builder.append("entity HasAuthor {");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("author: VARCHAR(1000)");
      _builder.newLine();
      _builder.append("} ");
      _builder.newLine();
      _builder.append("entity Post extends HasAuthor {");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("title: VARCHAR(1000)");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("content: VARCHAR(1000)");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("many Comment: INT");
      _builder.newLine();
      _builder.append("} ");
      _builder.newLine();
      _builder.append("entity Comment extends HasAuthor {");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("content: VARCHAR(1000)");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final Domainmodel result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assert.assertTrue(_builder_1.toString(), errors.isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void loadModel2() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("DATABASE name MarketDB");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("entity Market {");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("title: VARCHAR(100)");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("many Products: INT");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("entity HasEmployee {");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("name: VARCHAR(100)");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("salary: NUMBER");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("entity Products {");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("name: VARCHAR(1000)");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("description: VARCHAR(1000)");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("price: NUMBER");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      final Domainmodel result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assert.assertTrue(_builder_1.toString(), errors.isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void loadModel3() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("DATABASE name varchar");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("entity LibraryDB{");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("title: VARCHAR(100)");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("entity Author{");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("name: VARCHAR(100)");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("age: INT");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("entity Book extends Author{");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("name: VARCHAR(100)");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("description: TEXT(150)");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("company: VARCHAR(100)");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("id_author: INT\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      final Domainmodel result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assert.assertTrue(_builder_1.toString(), errors.isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void loadModel4() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("DATABASE name SchoolDB");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("entity Discipline {");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("title VARCHAR(100)");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("many students INT");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("entity Teacher extends Discipline{");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("name VARCHAR(100)");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("age INT");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("specialty VARCHAR(50)");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("entity Student extends Discipline{");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("id: INT");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("name: VARCHAR(100)");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("entity Note extends Student{");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("value: NUMBER");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      final Domainmodel result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assert.assertTrue(_builder_1.toString(), errors.isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
